#### Hostname : sonoff-txt02c-05
#### Friendly Name : hall-_bedroom
#### Last Modified : 2023-05-14

esphome:
  name: sonoff-txt02c-05
  comment: "SONOFF Switch TX T0 2C Hall Right Side"
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret home_ssid
  password: !secret home_ssid_password
  power_save_mode: none
  fast_connect: off
  use_address: !secret ip_address
  manual_ip:
    static_ip: !secret ip_address
    gateway: !secret gateway
    subnet: !secret subnet
    dns1: !secret dns1
    dns2: !secret dns2
  ap:
    ssid: "SONOFF_TX_T0_2C_03"
    password: !secret esp_ap_password

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: "Europe/Madrid"

captive_portal:

logger:
  level: INFO

api:
  encryption:
    key: !secret esphome_api_key

ota:
  safe_mode: True
  password: !secret esphome_ota_password

#web_server:
#  port: 8888
#  auth:
#    username: !secret esphome_web_server_username
#    password: !secret esphome_web_server_password

mqtt:
  broker: !secret mqtt
  port: 1883
  discovery: True
  discovery_retain: True
  discovery_prefix: "homeassistant"
  topic_prefix: home/indoors/hall/bedroom
  on_message:
    - topic: home/indoors/bedroom_1/switch/ceiling_bathroom/num_state
      payload: "1"
      then:
        - switch.turn_on: relay_1
        - delay: 1s
    - topic: home/indoors/bedroom_1/switch/ceiling_bathroom/num_state
      payload: "0"
      then:
        - switch.turn_off: relay_1
        - delay: 1s
    - topic: home/indoors/hall/switch/ceiling/num_state
      payload: "1"
      then:
        - switch.turn_on: relay_2
        - delay: 1s
    - topic: home/indoors/hall/switch/ceiling/num_state
      payload: "0"
      then:
        - switch.turn_off: relay_2
        - delay: 1s

sensor:
  #### WiFi signal level sensor
  - platform: wifi_signal
    name: "Hall Right Switch WiFi Level"
    update_interval: 60s

binary_sensor:
  - platform: status
    name: "Hall Right Switch Status"
  - platform: gpio
    name: "Hall Right Touchpad Bathroom"
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    filters:
      - delayed_on: 10ms
    on_press:
      - switch.toggle: relay_1
  - platform: gpio
    name: "Hall Right Touchpad Hall"
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: True
    filters:
      - delayed_on: 10ms
    on_press:
      - switch.toggle: relay_2

switch:
  - platform: restart
    name: "Hall Right Switch Restart"
  - platform: gpio
    name: "Hall Right Relay Bathroom Ceiling"
    pin: GPIO12
    id: relay_1
    on_turn_on:
      - mqtt.publish:
          topic: home/indoors/bedroom_1/switch/ceiling_bathroom/num_state
          payload: 1
    on_turn_off:
      - mqtt.publish:
          topic: home/indoors/bedroom_1/switch/ceiling_bathroom/num_state
          payload: 0
  - platform: gpio
    name: "Hall Right Relay Hall"
    pin: GPIO5
    id: relay_2
    on_turn_on:
      - mqtt.publish:
          topic: home/indoors/hall/switch/ceiling/num_state
          payload: 1
    on_turn_off:
      - mqtt.publish:
          topic: home/indoors/hall/switch/ceiling/num_state
          payload: 0

