#### Hostname : sonoff-minir2-02
#### Friendly Name : SONOFF Mini R2 02
#### Last Modified : 2023-05-14

esphome:
  name: toallero-bano-2
  comment: "SONOFF Mini R2 02"
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret home_ssid
  password: !secret home_ssid_password
  power_save_mode: none
  fast_connect: off
  use_address: !secret ip_address
  manual_ip:
    static_ip: !secret ip_address
    gateway: !secret gateway
    subnet: !secret subnet
    dns1: !secret dns1
    dns2: !secret dns2
  ap:
    ssid: "SONOFF_MINIR2_02"
    password: !secret esp_ap_password

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: "Europe/Madrid"

captive_portal:

logger:
  level: INFO

api:
  encryption:
    key: !secret esphome_api_key

ota:
  safe_mode: True
  password: !secret esphome_ota_password

sensor:
  - platform: wifi_signal
    name: "Toaller Ba単o 2 WiFi Level"
    update_interval: 60s

binary_sensor:
  - platform: status
    name: "SONOFF MINI R2 02 Status"
  - platform: gpio
    name: "Toallero Ba単o 2 Button"
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    filters:
      - delayed_on: 10ms
    on_press:
      - switch.toggle: relay_1

switch:
  - platform: restart
    name: "SONOFF MINI R2 02 Switch Restart"
  - platform: gpio
    name: "Toallero Ba単o 2 Relay"
    restore_mode: RESTORE_DEFAULT_OFF
    pin: GPIO12
    id: relay_1

output:
  - platform: esp8266_pwm
    id: blue_led
    pin: GPIO13
    inverted: True

light:
  - platform: status_led
    name: "Toallero Ba単o 2 LED"
    pin:
      number: GPIO13
      inverted: true

